# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  DocuWare:
    UUID: 02d1eec1-32e9-4316-afc3-793448486203
    Url: https://{host}/docuware/platform
    Icon: res:/webContent/icons/docuware.png
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    - org.glassfish.jersey.media.multipart.MultiPartFeature
    - com.axonivy.connector.docuware.connector.auth.OAuth2Feature
    Properties:
      PATH.host: ${ivy.var.docuwareConnector.host}
      UserName: ${ivy.var.docuwareConnector.username}
      Password: ${ivy.var.docuwareConnector.password}
      TrustedUserName: ${ivy.var.docuwareConnector.trustedUsername}
      TrustedUserPassword: ${ivy.var.docuwareConnector.trustedUserPassword}
      jersey.config.client.connectTimeout: ${ivy.var.docuwareConnector.connectTimeout}
      com.sun.jersey.impl.client.httpclient.handleCookies: 'true'
      http.protocol.handle-redirects: 'true'
      JSON.Serialization.PROPERTY_INCLUSION: NON_NULL
      jersey.config.client.logging.entity.maxSize: ${ivy.var.docuwareConnector.loggingEntityMaxSize}
    OpenAPI:
      SpecUrl: file:///X:/AxonIvy/marketplace/docuware/openapi-handmade.json
      Namespace: com.axonivy.connector.docuware.connector.model
